#!/bin/bash

#Stopping Existing React Processes
#sudo fuser -k 3000/tcp
#sudo fuser -k 3030/tcp

sudo apt update -y
#sudo yarn install -y

#cd /var/www/html/winetrust_2/packages/koa-app/
#sudo yarn dev
#sudo nohup bash -c 'yarn dev' &
#sudo touch yarn_dev.out
#sudo nohup bash -c 'yarn dev' > yarn_dev.out &
#netstat -an |grep 3030

cd /var/www/html/winetrust_2/packages/react-app/
#sudo touch yarn_start.out
sudo nohup bash -c 'yarn start' > yarn_start.out &
#sudo yarn start

#sudo nginx -t
#sudo systemctl restart nginx
